# Adapted from https://raw.githubusercontent.com/kaushalmodi/ox-hugo/master/.travis.yml
language: nix

# env:
#   global:
#     # - CURL="curl -fsSkL --retry 9 --retry-delay 9"
#     - OX_HUGO_TMP_DIR="/tmp/${USER}/ox-hugo-dev"
# - PANDOC_VERSION=2.5
# - EMACS_VERSION=26.1

# install:
# - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
# - tar xf emacs-bin-${EMACS_VERSION}.tar.gz -C /
# - export EMACS=/tmp/emacs/bin/emacs
# - $EMACS --version
# Add the yet-to-be Makefile downloaded pandoc to PATH
# - export PATH="${OX_HUGO_TMP_DIR}/pandoc/bin:${PATH}"
# - nix-shell

before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

before_script:
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf

script:
  - nix-shell --run "npm install && rake hugoBuild"

before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

cache:
  bundler: true
  nix: true
  npm: true
  directories:
    - /home/travis/build/HaoZeke/haozeke.github.io/.tmp/
    - $HOME/nix.store

deploy:
  provider: pages
  local_dir: ./public/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master # Required for user pages
  fqdn: rgoswami.me
  on:
    branch: src
